### ISSUE TITLE
[BUG] Latest versions of werkzeug break the application, prebuilt containers

### ISSUE THREAD

**Issue by jtavan** [reflexsoar/reflex-api#250]
**Describe the bug**
Current containers [(v2022.06.00-hf1)](https://hub.docker.com/layers/reflex-api/hasecuritysolutions/reflex-api/v2022.06.00-hf1/images/sha256-5175be050481631ce68d9c1b558749952946f4feb69822dc4dd1fe4172d81161?context=explore) are built with the latest version of werkzeug module, which includes breaking changes. 

**To Reproduce**
1. `docker run hasecuritysolutions/reflex-api:v2022.06.00-hf1`
2. Observe the following error:

```
 Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/-x-v5uFv0/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/__init__.py", line 6, in <module>
    from app.api_v2.model.system import Settings
  File "/app/api_v2/model/__init__.py", line 56, in <module>
    from .event import Event, EventRule, EventStatus
  File "/app/api_v2/model/event.py", line 7, in <module>
    from app.api_v2.rql.parser import QueryParser
  File "/app/api_v2/rql/__init__.py", line 1, in <module>
    from .base import RQLSearch, get_nested_field
  File "/app/api_v2/rql/base.py", line 5, in <module>
    from flask_restx import marshal
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/__init__.py", line 5, in <module>
    from .api import Api  # noqa
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/api.py", line 50, in <module>
    from .swagger import Swagger
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/swagger.py", line 18, in <module>
    from werkzeug.routing import parse_rule
ImportError: cannot import name 'parse_rule' from 'werkzeug.routing' (/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/werkzeug/routing/__init__.py)

```
**Expected behavior**
The Docker container should start up successfully and run the reflex-api application.

**Additional context**
See [this link](https://stackoverflow.com/questions/73105877/importerror-cannot-import-name-parse-rule-from-werkzeug-routing) for additional information. The solution for now appears to be to update Pipfile to lock werkzeug at version 2.1.2 (and possibly Flask as well)

**Comment by n3tsurge** [comment]
I meant to pull this HF it's not meant to be live yet.  Can you revert back? This issue is fixed in 2022.08.00 expected shortly.  2022.06.01-HF1 fixed one item and introduced this

Brian Carroll
________________________________
From: Jeremy Tavan ***@***.***>
Sent: Monday, August 29, 2022 8:08:21 PM
To: reflexsoar/reflex-api ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [reflexsoar/reflex-api] [BUG] Latest versions of werkzeug break the application, prebuilt containers (Issue #250)


Describe the bug
Current containers (v2022.06.00-hf1)<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhub.docker.com%2Flayers%2Freflex-api%2Fhasecuritysolutions%2Freflex-api%2Fv2022.06.00-hf1%2Fimages%2Fsha256-5175be050481631ce68d9c1b558749952946f4feb69822dc4dd1fe4172d81161%3Fcontext%3Dexplore&data=05%7C01%7Cbcarroll%40zeroonesecurity.com%7C394564cad39d4a6cc8a008da8a1bc038%7Ca68b09e0c76f40ccb262ae8575779491%7C0%7C0%7C637974149068805861%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DYD4OocXXsJK8WSQXHPcut6dOBMPo0kS3dD4gHiA7eg%3D&reserved=0> are built with the latest version of werkzeug module, which includes breaking changes.

To Reproduce
Steps to reproduce the behavior:

  1.  docker run hasecuritysolutions/reflex-api:v2022.06.00-hf1
  2.  Observe the following error:

 Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/-x-v5uFv0/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/__init__.py", line 6, in <module>
    from app.api_v2.model.system import Settings
  File "/app/api_v2/model/__init__.py", line 56, in <module>
    from .event import Event, EventRule, EventStatus
  File "/app/api_v2/model/event.py", line 7, in <module>
    from app.api_v2.rql.parser import QueryParser
  File "/app/api_v2/rql/__init__.py", line 1, in <module>
    from .base import RQLSearch, get_nested_field
  File "/app/api_v2/rql/base.py", line 5, in <module>
    from flask_restx import marshal
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/__init__.py", line 5, in <module>
    from .api import Api  # noqa
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/api.py", line 50, in <module>
    from .swagger import Swagger
  File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/swagger.py", line 18, in <module>
    from werkzeug.routing import parse_rule
ImportError: cannot import name 'parse_rule' from 'werkzeug.routing' (/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/werkzeug/routing/__init__.py)



Expected behavior
The Docker container should start up successfully and run the reflex-api application.

Additional context
See this link<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F73105877%2Fimporterror-cannot-import-name-parse-rule-from-werkzeug-routing&data=05%7C01%7Cbcarroll%40zeroonesecurity.com%7C394564cad39d4a6cc8a008da8a1bc038%7Ca68b09e0c76f40ccb262ae8575779491%7C0%7C0%7C637974149068805861%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FVko6CD%2FOSn6WxsUvmyln%2FPNTkfUnEIDzaw7T7Hp5po%3D&reserved=0> for additional information. The solution for now appears to be to update Pipfile to lock werkzeug at version 2.1.2 (and possibly Flask as well)

**Comment by jtavan** [comment]
I just pulled the code, modified Pipfile, rebuilt container, and it's back up.

**Comment by n3tsurge** [comment]
Okay, gonna close this out since I removed the HF release and it's already fixed in the next release here in a couple weeks.  Sorry for the issue
