### ISSUE TITLE
Events Queue Page isn't loading | getting 500 (INTERNAL SERVER ERROR)

### ISSUE THREAD

**Issue by greycel** [reflexsoar/reflex-api#408]
I've finished the setup and configured the Credentials. Inputs, Agents, and records are coming through as they should.

Event Queue was initially loading and populating the captured records.
Later today noticed that the Events Queue Page isn't loading and started to get 500 (INTERNAL SERVER ERROR) 

> Errors from inspect view:
![image](https://github.com/reflexsoar/reflex-api/assets/11851504/6fd7098c-32f7-48c9-8d88-d6ec17db5b97)
 

> Reflex-API Container logs:
```
Error while accessing Event Queue Page: 
#################################
reflex_ui     | 192.168.11.145 - - [13/Jun/2023:07:47:00 +0000] "GET /api/v2.0/close_reason HTTP/1.1" 200 429 "https://192.168.11.145:8443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "-"
reflex_api    | 2023-06-13 07:47:00,567 - opensearch - WARNING - POST https://192.168.11.126:9200/reflex-events/_search [status:400 request:0.011s]
reflex_api    | [2023-06-13 07:47:00 +0000] [16] [ERROR] Exception on /api/v2.0/event/stats [GET]
reflex_api    | Traceback (most recent call last):
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
reflex_api    |     rv = self.dispatch_request()
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
reflex_api    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/api.py", line 403, in wrapper
reflex_api    |     resp = resource(*args, **kwargs)
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/views.py", line 84, in view
reflex_api    |     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/resource.py", line 49, in dispatch_request
reflex_api    |     resp = meth(*args, **kwargs)
reflex_api    |   File "/app/api_v2/utils.py", line 213, in wrapper
reflex_api    |     return f(*args, **kwargs, current_user=current_user)
reflex_api    |   File "/app/api_v2/utils.py", line 259, in wrapper
reflex_api    |     return f(*args, **kwargs)
reflex_api    |   File "/app/api_v2/resource/event.py", line 1421, in get
reflex_api    |     events = search.execute()
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearch_dsl/search.py", line 721, in execute
reflex_api    |     opensearch.search(
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/client/utils.py", line 177, in _wrapped
reflex_api    |     return func(*args, params=params, headers=headers, **kwargs)
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/client/__init__.py", line 1593, in search
reflex_api    |     return self.transport.perform_request(
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/transport.py", line 407, in perform_request
reflex_api    |     raise e
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/transport.py", line 368, in perform_request
reflex_api    |     status, headers_response, data = connection.perform_request(
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/connection/http_urllib3.py", line 275, in perform_request
reflex_api    |     self._raise_error(
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/connection/base.py", line 300, in _raise_error
reflex_api    |     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
reflex_api    | opensearchpy.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'failed to create query: empty String')
reflex_api    | 2023-06-13 07:47:00,568 - app - ERROR - Exception on /api/v2.0/event/stats [GET]
reflex_api    | Traceback (most recent call last):
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
reflex_api    |     rv = self.dispatch_request()
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
reflex_api    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/api.py", line 403, in wrapper
reflex_api    |     resp = resource(*args, **kwargs)
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/views.py", line 84, in view
reflex_api    |     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/resource.py", line 49, in dispatch_request
reflex_api    |     resp = meth(*args, **kwargs)
reflex_api    |   File "/app/api_v2/utils.py", line 213, in wrapper
reflex_api    |     return f(*args, **kwargs, current_user=current_user)
reflex_api    |   File "/app/api_v2/utils.py", line 259, in wrapper
reflex_api    |     return f(*args, **kwargs)
reflex_api    |   File "/app/api_v2/resource/event.py", line 1421, in get
reflex_api    |     events = search.execute()
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearch_dsl/search.py", line 721, in execute
reflex_api    |     opensearch.search(
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/client/utils.py", line 177, in _wrapped
reflex_api    |     return func(*args, params=params, headers=headers, **kwargs)
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/client/__init__.py", line 1593, in search
reflex_api    |     return self.transport.perform_request(
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/transport.py", line 407, in perform_request
reflex_api    |     raise e
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/transport.py", line 368, in perform_request
reflex_api    |     status, headers_response, data = connection.perform_request(
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/connection/http_urllib3.py", line 275, in perform_request
reflex_api    |     self._raise_error(
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/connection/base.py", line 300, in _raise_error
reflex_api    |     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
reflex_api    | opensearchpy.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'failed to create query: empty String')
reflex_ui     | 192.168.11.145 - - [13/Jun/2023:07:47:00 +0000] "GET /api/v2.0/event/stats?q=&status=&severity=&metrics=title,observable,source,tag,status,severity,data_type,organization,event_rule,signature HTTP/1.1" 500 37 "https://192.168.11.145:8443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "-"
reflex_api    | 2023-06-13 07:47:00,573 - opensearch - WARNING - POST https://192.168.11.126:9200/reflex-events/_count [status:400 request:0.011s]
reflex_ui     | 192.168.11.145 - - [13/Jun/2023:07:47:00 +0000] "GET /api/v2.0/settings HTTP/1.1" 200 938 "https://192.168.11.145:8443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "-"
reflex_api    | [2023-06-13 07:47:00 +0000] [18] [ERROR] Exception on /api/v2.0/event [GET]
reflex_api    | Traceback (most recent call last):
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
reflex_api    |     rv = self.dispatch_request()
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
reflex_api    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/api.py", line 403, in wrapper
reflex_api    |     resp = resource(*args, **kwargs)
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/views.py", line 84, in view
reflex_api    |     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/resource.py", line 49, in dispatch_request
reflex_api    |     resp = meth(*args, **kwargs)
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/marshalling.py", line 248, in wrapper
reflex_api    |     resp = f(*args, **kwargs)
reflex_api    |   File "/app/api_v2/utils.py", line 213, in wrapper
reflex_api    |     return f(*args, **kwargs, current_user=current_user)
reflex_api    |   File "/app/api_v2/utils.py", line 259, in wrapper
reflex_api    |     return f(*args, **kwargs)
reflex_api    |   File "/app/api_v2/resource/event.py", line 285, in get
reflex_api    |     raw_event_count = search.count()
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearch_dsl/search.py", line 706, in count
reflex_api    |     return opensearch.count(index=self._index, body=d, **self._params)["count"]
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/client/utils.py", line 177, in _wrapped
reflex_api    |     return func(*args, params=params, headers=headers, **kwargs)
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/client/__init__.py", line 497, in count
reflex_api    |     return self.transport.perform_request(
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/transport.py", line 407, in perform_request
reflex_api    |     raise e
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/transport.py", line 368, in perform_request
reflex_api    |     status, headers_response, data = connection.perform_request(
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/connection/http_urllib3.py", line 275, in perform_request
reflex_api    |     self._raise_error(
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/connection/base.py", line 300, in _raise_error
reflex_api    |     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
reflex_api    | opensearchpy.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'failed to create query: empty String')
reflex_api    | 2023-06-13 07:47:00,574 - app - ERROR - Exception on /api/v2.0/event [GET]
reflex_api    | Traceback (most recent call last):
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
reflex_api    |     rv = self.dispatch_request()
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
reflex_api    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/api.py", line 403, in wrapper
reflex_api    |     resp = resource(*args, **kwargs)
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/views.py", line 84, in view
reflex_api    |     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/resource.py", line 49, in dispatch_request
reflex_api    |     resp = meth(*args, **kwargs)
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/marshalling.py", line 248, in wrapper
reflex_api    |     resp = f(*args, **kwargs)
reflex_api    |   File "/app/api_v2/utils.py", line 213, in wrapper
reflex_api    |     return f(*args, **kwargs, current_user=current_user)
reflex_api    |   File "/app/api_v2/utils.py", line 259, in wrapper
reflex_api    |     return f(*args, **kwargs)
reflex_api    |   File "/app/api_v2/resource/event.py", line 285, in get
reflex_api    |     raw_event_count = search.count()
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearch_dsl/search.py", line 706, in count
reflex_api    |     return opensearch.count(index=self._index, body=d, **self._params)["count"]
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/client/utils.py", line 177, in _wrapped
reflex_api    |     return func(*args, params=params, headers=headers, **kwargs)
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/client/__init__.py", line 497, in count
reflex_api    |     return self.transport.perform_request(
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/transport.py", line 407, in perform_request
reflex_api    |     raise e
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/transport.py", line 368, in perform_request
reflex_api    |     status, headers_response, data = connection.perform_request(
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/connection/http_urllib3.py", line 275, in perform_request
reflex_api    |     self._raise_error(
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/connection/base.py", line 300, in _raise_error
reflex_api    |     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
reflex_api    | opensearchpy.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'failed to create query: empty String')
reflex_ui     | 192.168.11.145 - - [13/Jun/2023:07:47:00 +0000] "GET /api/v2.0/event?grouped=true&sort_by=created_at&sort_direction=desc&status=&search=&severity=&page=1&page_size=10 HTTP/1.1" 500 37 "https://192.168.11.145:8443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "-"
reflex_ui     | 192.168.11.145 - - [13/Jun/2023:07:47:00 +0000] "GET /api/v2.0/organization?page=1&page_size=100&sort_by=created_at&sort_direction=asc HTTP/1.1" 200 303 "https://192.168.11.145:8443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "-"
reflex_ui     | 192.168.11.145 - - [13/Jun/2023:07:47:00 +0000] "GET /favicon-32x32.png HTTP/1.1" 200 1285 "https://192.168.11.145:8443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "-"
reflex_ui     | 192.168.11.145 - - [13/Jun/2023:07:47:03 +0000] "GET /api/v2.0/task?complete=true&broadcast=true HTTP/1.1" 200 14 "https://192.168.11.145:8443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "-"
```

Any advice on what might have gone wrong...

**Comment by n3tsurge** [comment]
There are probably quite a few bugs you are hitting that we resolved in this most recent release coming up.  I know you just got this working but can you 

1. Take down your containers
2. Delete the reflex-* indices
3. Change your image tags to `version-2023.06.06-rc0`
4. Restart your containers?

This is a stable version of the build we run internally.

**Comment by greycel** [comment]
Thank you, will check the new release..


Currently used docker images (reflex-ui, reflex-api) that being with `zeroonesec` and configured for it with my existing OpenSearch Instance as persistent storage, whereas quick start compose file points to a different images that being with
` hasecuritysolutions/ (reflex-ui, reflex-api, reflex-agent) `


What's the differences in images that being with: ` zeroonesec & hasecuritysolutions `

Will there be any major changes in reflex-app..

**Comment by n3tsurge** [comment]
Nothing, one is built via docker hub, one is built via GitHub actions.  They are essentially the same

Sent from my Verizon, Samsung Galaxy s
________________________________

**Comment by greycel** [comment]
I've pulled the stable version tagged ```version-2023.06.06-rc0``` and everything seems to be up and running

Noticed that the ```reflex-api``` service keeps throwing this SSLerror ```urllib3.exceptions.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2607)``` when connecting to OpenSearch instance

```
reflex_ui     | 192.168.11.145- - [15/Jun/2023:10:07:51 +0000] "GET /js/chunk-2d0a4b20.248beb0b.js HTTP/1.1" 200 2059 "https://192.168.11.226/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
reflex_api    | 2023-06-15 10:07:51,822 - opensearch - WARNING - POST https://192.168.11.126:9200/reflex-mitre-techniques-0.1.4/_update/dakVvogBAGtC4YQQxUMj?refresh=true [status:N/A request:0.010s]
reflex_api    | Traceback (most recent call last):
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
reflex_api    |     httplib_response = self._make_request(
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
reflex_api    |     six.raise_from(e, None)
reflex_api    |   File "<string>", line 3, in raise_from
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
reflex_api    |     httplib_response = conn.getresponse()
reflex_api    |   File "/usr/local/lib/python3.8/http/client.py", line 1322, in getresponse
reflex_api    |     response.begin()
reflex_api    |   File "/usr/local/lib/python3.8/http/client.py", line 303, in begin
reflex_api    |     version, status, reason = self._read_status()
reflex_api    |   File "/usr/local/lib/python3.8/http/client.py", line 272, in _read_status
reflex_api    |     raise RemoteDisconnected("Remote end closed connection without"
reflex_api    | http.client.RemoteDisconnected: Remote end closed connection without response
reflex_api    |
reflex_api    | During handling of the above exception, another exception occurred:
reflex_api    |
reflex_api    | Traceback (most recent call last):
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/connection/http_urllib3.py", line 249, in perform_request
reflex_api    |     response = self.pool.urlopen(
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
reflex_api    |     retries = retries.increment(
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/urllib3/util/retry.py", line 525, in increment
reflex_api    |     raise six.reraise(type(error), error, _stacktrace)
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
reflex_api    |     raise value.with_traceback(tb)
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
reflex_api    |     httplib_response = self._make_request(
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
reflex_api    |     six.raise_from(e, None)
reflex_api    |   File "<string>", line 3, in raise_from
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
reflex_api    |     httplib_response = conn.getresponse()
reflex_api    |   File "/usr/local/lib/python3.8/http/client.py", line 1322, in getresponse
reflex_api    |     response.begin()
reflex_api    |   File "/usr/local/lib/python3.8/http/client.py", line 303, in begin
reflex_api    |     version, status, reason = self._read_status()
reflex_api    |   File "/usr/local/lib/python3.8/http/client.py", line 272, in _read_status
reflex_api    |     raise RemoteDisconnected("Remote end closed connection without"
reflex_api    | urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
reflex_api    | 2023-06-15 10:07:51,823 - opensearch - WARNING - POST https://192.168.11.126:9200/reflex-expired-tokens/_search [status:N/A request:0.004s]
reflex_api    | Traceback (most recent call last):
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
reflex_api    |     httplib_response = self._make_request(
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
reflex_api    |     six.raise_from(e, None)
reflex_api    |   File "<string>", line 3, in raise_from
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
reflex_api    |     httplib_response = conn.getresponse()
reflex_api    |   File "/usr/local/lib/python3.8/http/client.py", line 1322, in getresponse
reflex_api    |     response.begin()
reflex_api    |   File "/usr/local/lib/python3.8/http/client.py", line 303, in begin
reflex_api    |     version, status, reason = self._read_status()
reflex_api    |   File "/usr/local/lib/python3.8/http/client.py", line 264, in _read_status
reflex_api    |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
reflex_api    |   File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
reflex_api    |     return self._sock.recv_into(b)
reflex_api    |   File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
reflex_api    |     return self.read(nbytes, buffer)
reflex_api    |   File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
reflex_api    |     return self._sslobj.read(len, buffer)
reflex_api    | ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2607)
reflex_api    |
reflex_api    | During handling of the above exception, another exception occurred:
reflex_api    |
reflex_api    | Traceback (most recent call last):
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/connection/http_urllib3.py", line 249, in perform_request
reflex_api    |     response = self.pool.urlopen(
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
reflex_api    |     retries = retries.increment(
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/urllib3/util/retry.py", line 525, in increment
reflex_api    |     raise six.reraise(type(error), error, _stacktrace)
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
reflex_api    |     raise value.with_traceback(tb)
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
reflex_api    |     httplib_response = self._make_request(
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
reflex_api    |     six.raise_from(e, None)
reflex_api    |   File "<string>", line 3, in raise_from
reflex_api    |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
reflex_api    |     httplib_response = conn.getresponse()
reflex_api    |   File "/usr/local/lib/python3.8/http/client.py", line 1322, in getresponse
reflex_api    |     response.begin()
reflex_api    |   File "/usr/local/lib/python3.8/http/client.py", line 303, in begin
reflex_api    |     version, status, reason = self._read_status()
reflex_api    |   File "/usr/local/lib/python3.8/http/client.py", line 264, in _read_status
reflex_api    |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
reflex_api    |   File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
reflex_api    |     return self._sock.recv_into(b)
reflex_api    |   File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
reflex_api    |     return self.read(nbytes, buffer)
reflex_api    |   File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
reflex_api    |     return self._sslobj.read(len, buffer)
reflex_api    | urllib3.exceptions.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:2607)
reflex_ui     | 172.27.0.1 - - [15/Jun/2023:10:07:51 +0000] "GET /api/v2.0/agent/aa70dd28-023b-4b39-ab2a-9d2531060929 HTTP/1.1" 401 30 "-" "reflexsoar-agent/2022.05.01" "-"
reflex_ui     | 192.168.11.145 - - [15/Jun/2023:10:07:51 +0000] "GET /js/chunk-2d0b2ece.eb127f8a.js HTTP/1.1" 200 423 "https://192.168.11.226/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"

```

**Comment by n3tsurge** [comment]
Glad it's working.  This error is safe to ignore.
