### ISSUE TITLE
SOC Reporting isn't working

### ISSUE THREAD

**Issue by greycel** [reflexsoar/reflex-api#437]
Hi Team,

The SOC Reporting option isn't working, getting `opensearchpy.exceptions.RequestError` in backed logs
Using latest version [v2023.08.07-rc0](https://github.com/reflexsoar/reflex-api/releases/tag/v2023.08.07-rc0)

```
reflex_api  | Checking detection repository subscriptions for sync
reflex_api  | Checking detection repository subscriptions for sync
reflex_api  | 2023-08-23 14:43:12,287 - opensearch - WARNING - POST https://192.168.5.150:9200/reflex-events/_search [status:400 request:0.003s]
reflex_api  | [2023-08-23 14:43:12 +0000] [45] [ERROR] Exception on /api/v2.0/reporting/0aa111cc-00c6-4aeb-b948-d2b44c76bcee [GET]
reflex_api  | Traceback (most recent call last):
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
reflex_api  |     rv = self.dispatch_request()
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
reflex_api  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/api.py", line 404, in wrapper
reflex_api  |     resp = resource(*args, **kwargs)
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/views.py", line 84, in view
reflex_api  |     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/resource.py", line 46, in dispatch_request
reflex_api  |     resp = meth(*args, **kwargs)
reflex_api  |   File "/app/api_v2/utils.py", line 227, in wrapper
reflex_api  |     return f(*args, **kwargs, current_user=current_user)
reflex_api  |   File "/app/api_v2/utils.py", line 247, in wrapper
reflex_api  |     return f(*args, **kwargs)
reflex_api  |   File "/app/api_v2/resource/reporting.py", line 103, in get
reflex_api  |     top_events_search = top_events_search.execute()
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearch_dsl/search.py", line 721, in execute
reflex_api  |     opensearch.search(
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/client/utils.py", line 177, in _wrapped
reflex_api  |     return func(*args, params=params, headers=headers, **kwargs)
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/client/__init__.py", line 1593, in search
reflex_api  |     return self.transport.perform_request(
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/transport.py", line 407, in perform_request
reflex_api  |     raise e
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/transport.py", line 368, in perform_request
reflex_api  |     status, headers_response, data = connection.perform_request(
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/connection/http_urllib3.py", line 275, in perform_request
reflex_api  |     self._raise_error(
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/connection/base.py", line 300, in _raise_error
reflex_api  |     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
reflex_api  | opensearchpy.exceptions.RequestError: RequestError(400, 'x_content_parse_exception', '[1:240] [bool] failed to parse field [filter]')
reflex_api  | 2023-08-23 14:43:12,289 - app - ERROR - Exception on /api/v2.0/reporting/0aa111cc-00c6-4aeb-b948-d2b44c76bcee [GET]
reflex_api  | Traceback (most recent call last):
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
reflex_api  |     rv = self.dispatch_request()
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
reflex_api  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/api.py", line 404, in wrapper
reflex_api  |     resp = resource(*args, **kwargs)
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask/views.py", line 84, in view
reflex_api  |     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/flask_restx/resource.py", line 46, in dispatch_request
reflex_api  |     resp = meth(*args, **kwargs)
reflex_api  |   File "/app/api_v2/utils.py", line 227, in wrapper
reflex_api  |     return f(*args, **kwargs, current_user=current_user)
reflex_api  |   File "/app/api_v2/utils.py", line 247, in wrapper
reflex_api  |     return f(*args, **kwargs)
reflex_api  |   File "/app/api_v2/resource/reporting.py", line 103, in get
reflex_api  |     top_events_search = top_events_search.execute()
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearch_dsl/search.py", line 721, in execute
reflex_api  |     opensearch.search(
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/client/utils.py", line 177, in _wrapped
reflex_api  |     return func(*args, params=params, headers=headers, **kwargs)
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/client/__init__.py", line 1593, in search
reflex_api  |     return self.transport.perform_request(
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/transport.py", line 407, in perform_request
reflex_api  |     raise e
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/transport.py", line 368, in perform_request
reflex_api  |     status, headers_response, data = connection.perform_request(
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/connection/http_urllib3.py", line 275, in perform_request
reflex_api  |     self._raise_error(
reflex_api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/connection/base.py", line 300, in _raise_error
reflex_api  |     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
reflex_api  | opensearchpy.exceptions.RequestError: RequestError(400, 'x_content_parse_exception', '[1:240] [bool] failed to parse field [filter]')
reflex_api  | Checking detection repository subscriptions for sync
reflex_api  | Checking detection repository subscriptions for sync
```

Any advice on workarounds would be helpful...

**Comment by n3tsurge** [comment]
Is this the first time trying to run it or has it worked previously?

If it's the first time can you go in to the Organizaton Settings and ensure the timezone is selected?  Sometimes if it hasn't been set yet it can cause the report to fail

![2023-08-23_11-19-57](https://github.com/reflexsoar/reflex-api/assets/1574741/cf4d4b19-02af-4c59-8f80-046fb4d9c83b)

**Comment by greycel** [comment]
Yeah, this is the first time I've checked the reporting option.
I've just enabled it time-zone, but the behavior remains - getting the same error in the backend logs

**Comment by n3tsurge** [comment]
I am assuming you are in a + offset as I am able to replicate this with an utc offset that is a +.  I have a fix it, it will come in our next dev release.  For now can you workaround the issue by using a - timezone?   Sorry for the inconvenience.

**Comment by n3tsurge** [comment]
Fixed in latest Release Candidate
