### ISSUE TITLE
Unable to install reflex on AWS Managed Elastic 

### ISSUE THREAD

**Issue by greycel** [reflexsoar/reflex-api#463]
Hi Team,

unable to set up on AWS, getting `AuthenticationException` while trying to run the reflex setup on AWS Managed OpenSearch Instance, same worked locally.

Had to change the API connection port from `9200` to `443`, as the instance only connects over HTTPS, 
 `curl` command is working fine with the credentials passed but the same isn't not working when initiating through API.

API Environment Variables
```
      - REFLEX_ES_URL=vpc-xxxx-xxxxxxxxxxxx.xxx-xxx.xxx.amazonaws.com:443
      - REFLEX_ES_USERNAME=xxxxxxx
      - REFLEX_ES_PASSWORD=xxxxxxxxxxxxxx
      - REFLEX_ES_DISTRO=opensearch
      - REFLEX_ES_AUTH_SCHEMA=https
      - REFLEX_ES_CERT_VERIFY=false
      - REFLEX_LOG_LEVEL=DEBUG
      - REFLEX_ES_TIMEOUT=120
```

API Error
```
reflex-api  | 2023-11-28 06:23:08,408 - opensearch - WARNING - HEAD https://vpc-xxxx-xxxxxxxxxxxx.xxx-xxx.xxx.amazonaws.com:443/reflex-settings [status:401 request:0.015s]
reflex-api  | [Errno 2] No such file or directory: '/app/version.txt'
reflex-api  | Traceback (most recent call last):
reflex-api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/bin/gunicorn", line 8, in <module>
reflex-api  |     sys.exit(run())
reflex-api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
reflex-api  |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
reflex-api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/app/base.py", line 236, in run
reflex-api  |     super().run()
reflex-api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
reflex-api  |     Arbiter(self).run()
reflex-api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/arbiter.py", line 58, in __init__
reflex-api  |     self.setup(app)
reflex-api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/arbiter.py", line 118, in setup
reflex-api  |     self.app.wsgi()
reflex-api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
reflex-api  |     self.callable = self.load()
reflex-api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
reflex-api  |     return self.load_wsgiapp()
reflex-api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
reflex-api  |     return util.import_app(self.app_uri)
reflex-api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/gunicorn/util.py", line 424, in import_app
reflex-api  |     app = app(*args, **kwargs)
reflex-api  |   File "/app/__init__.py", line 293, in create_app
reflex-api  |     if setup_complete() != True:
reflex-api  |   File "/app/__init__.py", line 187, in setup_complete
reflex-api  |     return es.indices.exists('reflex-settings')
reflex-api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/client/utils.py", line 177, in _wrapped
reflex-api  |     return func(*args, params=params, headers=headers, **kwargs)
reflex-api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/client/indices.py", line 331, in exists
reflex-api  |     return self.transport.perform_request(
reflex-api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/transport.py", line 407, in perform_request
reflex-api  |     raise e
reflex-api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/transport.py", line 368, in perform_request
reflex-api  |     status, headers_response, data = connection.perform_request(
reflex-api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/connection/http_urllib3.py", line 275, in perform_request
reflex-api  |     self._raise_error(
reflex-api  |   File "/root/.local/share/virtualenvs/-x-v5uFv0/lib/python3.8/site-packages/opensearchpy/connection/base.py", line 300, in _raise_error
reflex-api  |     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
reflex-api  | opensearchpy.exceptions.AuthenticationException: AuthenticationException(401, '')
```

Is there any additional configuration change I can try to get this working on the AWS environment, pls advice.

**Comment by n3tsurge** [comment]
Change your auth scheme to http, https is not a valid auth scheme.  http just means basic auth.  If it's using API keys instead of basic auth you can set it to api-key instead.  You may also have to supply https:// on the front of your URL

**Comment by n3tsurge** [comment]
You may also have to set REFLEX_ES_USE_TLS=true.  I'll check our production config in a few hours when our morning starts, we do all our connections over https by default.

**Comment by greycel** [comment]
Thank you very much, it worked...
